CREATE TABLE pacientes(

id BIGINT NOT NULL AUTO_INCREMENT,
nombre VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
documentoIdentidad VARCHAR(6) NOT NULL UNIQUE,
telefono VARCHAR(20) NOT NULL,
urbanización VARCHAR(100) NOT NULL,
calle VARCHAR(100) NOT NULL,
distrito VARCHAR(100) NOT NULL,
codigoPostal VARCHAR(9) NOT NULL,
complemento VARCHAR(100) NOT NULL,
numero VARCHAR(20),
provincia varchar(100) NOT NULL,
ciudad VARCHAR(100) NOT NULL,

PRIMARY KEY(id)
);